### ISSUE TITLE
Crossover release TODO

### ISSUE THREAD

**Issue by Knallertton** [TeamKoprulu/SCEvoComplete#13]
### Evo Core
- [x] add bunker salvage (Core)
- [x] Add new Reaver mechanics

### Evo Extension (SC1 vs SC2 Races)
- [x] Dark archon feedback deals full damage (Instead of 0.5 per damage
- [x] Add water balloon attack for SC1 High Templar and Dark Archon (Core)
- [x] Changeling doesn't mimic to SC1 Races 
- [x] Add sc2 Turret tracking for sc1 siege tank
- [x] Combine terran ship and vehicle armors to one upgrade
- [x] Add surveillance mode to sc1 obs (Core)
- [x] Match ultralisk size to sc2 ultralisk
- [x] Verify that Ultralisk has burrow on Extension
- [x] Match guardian range to tempest ground range
- [x] Check zealot legs matches speed the sc2 one (make it slightly better due to no charge component)
- [x] Buff SC1 High templar acceleration
- [x] Rework Dark Swarm
- [x] Add Stinger (Core)
     - [x] Requires machine shop (test balance)
- [x] Add Stinger Attack while moving Upgrade
- [x] Add Stinger Grenade Attack (Targets buildings only)
- [x] Add new queen creep ability
- [x] ensnare reveals targets in fog of war
- [x] ultralisk add frenzy buff
- [x] SiegeTankSCBW add +1 range
- [x] AI vipers can target sc1 interceptors with para bomb
- [ ] Add new abilities and techs to AI 
- [ ] Check niche sc2 interactions with abilities targeting larva and eggs that might need adjusting for SC1 Larva & Egg
- [x] Add confirmation UI for the Discord link button, to prevent accidental clicks during gameplay 
- [x] Set Hydralisk supply cost to 1
- [x] Adjust Photon cannon damage to match sc2
- [x] Adjust Missile Turret damage to match sc2
- [ ] Review all spell ranges
- [x] Increase creep generation of Hatchery, Lair and Hive by +1

### Evo Legacy Extension (SC1 Only)
