### ISSUE TITLE
Update 1.4 To-Do

### ISSUE THREAD

**Issue by Ailoso** [TeamKoprulu/SCEvoComplete#20]
Bugs

- [x] Missing Cancel button from warping in shield battery
- [ ] Remove confederate flag from game files
- [x] Fix broken textures from machine shop model
- [x] Fix missing mesh during lair morph animation

Additions

- [ ] Queen Nest Model
- [ ] Fixed Nuke silo model
